# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
#       - name: Set Environment Variables
#         env:
#           REACT_APP_COGNITO_USER_POOL_ID: ${{ secrets.REACT_APP_COGNITO_USER_POOL_ID }}
#           REACT_APP_COGNITO_USER_POOL_WEBCLIENT_ID: ${{ secrets.REACT_APP_COGNITO_USER_POOL_WEBCLIENT_ID }}
#           REACT_APP_COGNITO_AUTH_DOMAIN: ${{ secrets.REACT_APP_COGNITO_AUTH_DOMAIN }}
#           REACT_APP_REDIRECT_SIGNIN: ${{ secrets.REACT_APP_REDIRECT_SIGNIN }}
#           REACT_APP_REDIRECT_SIGNOUT: ${{ secrets.REACT_APP_REDIRECT_SIGNOUT }}
      - run: env
      - run: npm ci
      - name: REACT_APP_COGNITO_USER_POOL_ID
        ## Reference your environment variables
        run: echo "The API key is:${{env.REACT_APP_COGNITO_USER_POOL_ID}}" 
      - run: npm test -- --passWithNoTests
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
